<?php
/**
 * BetVibe - Quest Templates
 * Pool of 20+ quest templates for daily quest rotation
 */

return [
    // ─── Easy Quests (XP: 50-100, Coins: 10-25) ───
    [
        'key' => 'play_3_rounds',
        'title' => '3 Rounds Khel',
        'description' => 'Play any 3 rounds in any game',
        'difficulty' => 'easy',
        'xp_reward' => 50,
        'coin_reward' => 10,
        'condition' => ['type' => 'play_rounds', 'game' => 'any', 'count' => 3],
    ],
    [
        'key' => 'play_5_rounds',
        'title' => '5 Rounds Warrior',
        'description' => 'Play any 5 rounds in any game',
        'difficulty' => 'easy',
        'xp_reward' => 75,
        'coin_reward' => 15,
        'condition' => ['type' => 'play_rounds', 'game' => 'any', 'count' => 5],
    ],
    [
        'key' => 'win_1_bet',
        'title' => 'Ek Jeet',
        'description' => 'Win at least 1 bet today',
        'difficulty' => 'easy',
        'xp_reward' => 50,
        'coin_reward' => 10,
        'condition' => ['type' => 'win_bets', 'game' => 'any', 'count' => 1],
    ],
    [
        'key' => 'try_color_predict',
        'title' => 'Color Predict Explorer',
        'description' => 'Play a round of Color Predict',
        'difficulty' => 'easy',
        'xp_reward' => 60,
        'coin_reward' => 15,
        'condition' => ['type' => 'try_game', 'game' => 'color_predict', 'count' => 1],
    ],
    [
        'key' => 'try_crash',
        'title' => 'Crash Pilot',
        'description' => 'Play a round of Crash',
        'difficulty' => 'easy',
        'xp_reward' => 60,
        'coin_reward' => 15,
        'condition' => ['type' => 'try_game', 'game' => 'crash', 'count' => 1],
    ],
    [
        'key' => 'try_mines',
        'title' => 'Mine Sweeper',
        'description' => 'Play a round of Mines',
        'difficulty' => 'easy',
        'xp_reward' => 60,
        'coin_reward' => 15,
        'condition' => ['type' => 'try_game', 'game' => 'mines', 'count' => 1],
    ],
    [
        'key' => 'try_plinko',
        'title' => 'Plinko Dropper',
        'description' => 'Drop a ball in Plinko',
        'difficulty' => 'easy',
        'xp_reward' => 60,
        'coin_reward' => 15,
        'condition' => ['type' => 'try_game', 'game' => 'plinko', 'count' => 1],
    ],

    // ─── Medium Quests (XP: 100-200, Coins: 25-50) ───
    [
        'key' => 'win_3_bets',
        'title' => 'Hat-trick Hero',
        'description' => 'Win 3 bets in any game',
        'difficulty' => 'medium',
        'xp_reward' => 150,
        'coin_reward' => 30,
        'condition' => ['type' => 'win_bets', 'game' => 'any', 'count' => 3],
    ],
    [
        'key' => 'play_10_rounds',
        'title' => 'Grinder Mode',
        'description' => 'Play 10 rounds in any game',
        'difficulty' => 'medium',
        'xp_reward' => 120,
        'coin_reward' => 25,
        'condition' => ['type' => 'play_rounds', 'game' => 'any', 'count' => 10],
    ],
    [
        'key' => 'win_color_predict',
        'title' => 'Color King',
        'description' => 'Win 2 rounds in Color Predict',
        'difficulty' => 'medium',
        'xp_reward' => 150,
        'coin_reward' => 30,
        'condition' => ['type' => 'win_bets', 'game' => 'color_predict', 'count' => 2],
    ],
    [
        'key' => 'win_amount_100',
        'title' => 'Centurion',
        'description' => 'Win NPR 100+ total today',
        'difficulty' => 'medium',
        'xp_reward' => 150,
        'coin_reward' => 35,
        'condition' => ['type' => 'win_amount', 'amount' => 100, 'count' => 1],
    ],
    [
        'key' => 'play_3_games',
        'title' => 'Game Explorer',
        'description' => 'Play 3 different games today',
        'difficulty' => 'medium',
        'xp_reward' => 175,
        'coin_reward' => 40,
        'condition' => ['type' => 'play_different_games', 'count' => 3],
    ],
    [
        'key' => 'win_streak_3',
        'title' => 'On Fire!',
        'description' => 'Achieve a 3-win streak',
        'difficulty' => 'medium',
        'xp_reward' => 200,
        'coin_reward' => 50,
        'condition' => ['type' => 'win_streak', 'count' => 3],
    ],
    [
        'key' => 'play_fast_parity_5',
        'title' => 'Speed Demon',
        'description' => 'Play 5 rounds of Fast Parity',
        'difficulty' => 'medium',
        'xp_reward' => 130,
        'coin_reward' => 30,
        'condition' => ['type' => 'play_rounds', 'game' => 'fast_parity', 'count' => 5],
    ],

    // ─── Hard Quests (XP: 200-500, Coins: 50-100) ───
    [
        'key' => 'win_5_bets',
        'title' => 'Winning Machine',
        'description' => 'Win 5 bets today',
        'difficulty' => 'hard',
        'xp_reward' => 300,
        'coin_reward' => 75,
        'condition' => ['type' => 'win_bets', 'game' => 'any', 'count' => 5],
    ],
    [
        'key' => 'win_amount_500',
        'title' => 'Big Winner',
        'description' => 'Win NPR 500+ total today',
        'difficulty' => 'hard',
        'xp_reward' => 400,
        'coin_reward' => 80,
        'condition' => ['type' => 'win_amount', 'amount' => 500, 'count' => 1],
    ],
    [
        'key' => 'play_20_rounds',
        'title' => 'Marathon Runner',
        'description' => 'Play 20 rounds today',
        'difficulty' => 'hard',
        'xp_reward' => 250,
        'coin_reward' => 50,
        'condition' => ['type' => 'play_rounds', 'game' => 'any', 'count' => 20],
    ],
    [
        'key' => 'win_streak_5',
        'title' => 'Unstoppable',
        'description' => 'Achieve a 5-win streak',
        'difficulty' => 'hard',
        'xp_reward' => 500,
        'coin_reward' => 100,
        'condition' => ['type' => 'win_streak', 'count' => 5],
    ],
    [
        'key' => 'play_5_diff_games',
        'title' => 'All-Rounder',
        'description' => 'Play 5 different games today',
        'difficulty' => 'hard',
        'xp_reward' => 350,
        'coin_reward' => 70,
        'condition' => ['type' => 'play_different_games', 'count' => 5],
    ],
    [
        'key' => 'crash_3x_win',
        'title' => 'Crash Survivor',
        'description' => 'Win a Crash bet at 3x or higher multiplier',
        'difficulty' => 'hard',
        'xp_reward' => 400,
        'coin_reward' => 80,
        'condition' => ['type' => 'win_multiplier', 'game' => 'crash', 'min_multiplier' => 3.0, 'count' => 1],
    ],
    [
        'key' => 'win_10_bets',
        'title' => 'Legend',
        'description' => 'Win 10 bets today',
        'difficulty' => 'hard',
        'xp_reward' => 500,
        'coin_reward' => 100,
        'condition' => ['type' => 'win_bets', 'game' => 'any', 'count' => 10],
    ],
];
